
package Interface;
import javax.swing.JTable;
import java.util.Vector;
import DataTransferObject.*;
import javax.swing.table.DefaultTableModel;
import Process.*;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class SuaXe extends javax.swing.JFrame {

    MainForm mainForm = null;
    JTable table = null;
    /**
     * Creates new form SuaXe
     */
    public SuaXe() {
        initComponents();
        this.setDefaultCloseOperation(SuaXe.DISPOSE_ON_CLOSE);
    }
     public SuaXe(MainForm mainForm, JTable table) {
        initComponents();
        this.mainForm = mainForm;
        this.table = table;
        loadDataFromTable();
        this.setDefaultCloseOperation(SuaXe.DISPOSE_ON_CLOSE);
    }
    private void loadDataFromTable() {
        DefaultTableModel model = (DefaultTableModel) this.table.getModel();
        Vector data = (Vector) model.getDataVector().get(this.table.getSelectedRow());
        txtBienSo.setText((String) data.elementAt(0)); 
        txtLoaiXe.setText((String) data.elementAt(1)); 
        txtSoCho.setText(data.elementAt(2).toString()+ ""); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBienSo = new javax.swing.JLabel();
        txtSoCho = new javax.swing.JLabel();
        txtLoaiXe = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBienSo.setText("Biển số:");

        txtSoCho.setText("Số chỗ:");

        txtLoaiXe.setText("Loại xe:");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLoaiXe)
                            .addComponent(txtSoCho)
                            .addComponent(txtBienSo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnSua)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBienSo)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoCho)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiXe)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnSua)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
         boolean pass = true;

    // Kiểm tra Biển số
    String BienSo = txtBienSo.getText();
    if (BienSo.equals("")) {
        pass = false;
        JOptionPane.showMessageDialog(rootPane, "Biển số không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    // Kiểm tra Số chỗ
    int SoCho = 0;
    try {
        SoCho = Integer.parseInt(txtSoCho.getText());
        if (SoCho <= 0) {
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Số chỗ phải là số dương!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        pass = false;
        JOptionPane.showMessageDialog(rootPane, "Số chỗ không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    // Kiểm tra Loại xe
    String LoaiXe = txtLoaiXe.getText();
    if (LoaiXe.equals("")) {
        pass = false;
        JOptionPane.showMessageDialog(rootPane, "Loại xe không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    // Nếu các kiểm tra đều hợp lệ
    if (pass) {
        Xe xe = new Xe(BienSo, SoCho, LoaiXe); 
        BULXe bulXe = new BULXe();
        try {
            bulXe.suaXe(xe); 
            JOptionPane.showMessageDialog(rootPane, "Sửa xe thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Cập nhật giao diện
            this.setVisible(false);
            this.mainForm.updateTableXe(); // Giả sử hàm này cập nhật bảng danh sách xe
            this.dispose();
        } catch (Exception ex) {
            if (ex.toString().contains("Duplicate entry") && ex.toString().contains("BienSo")) {
                JOptionPane.showMessageDialog(rootPane, "Biển số đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println(ex);
                JOptionPane.showMessageDialog(rootPane, String.format("Đã có lỗi xảy ra! %s", ex), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel txtBienSo;
    private javax.swing.JLabel txtLoaiXe;
    private javax.swing.JLabel txtSoCho;
    // End of variables declaration//GEN-END:variables
}
